[WIP] branch Init / create component Lesson/Post.jsx
SouchetJulie/DevLab pull request #12
Opened 2022-01-20 23:57 UTC by EidanU

2022-01-21 08:10 UTC, SouchetJulie requested changes

2022-01-21 08:10 UTC, SouchetJulie commented on src/client/components/Lesson/Post.tsx
> +  lesson: any;
Utilise plutôt le type `ILesson` ;)

2022-01-21 08:10 UTC, SouchetJulie commented on src/client/components/Menu/SideBarContent.tsx
> +    <Form action={"/post"}>
J'ai vu que tu avais remplacé pleins de "lesson" par "post", mais c'est bien "lesson" en fait. "post" c'est juste le vieux nom qui avait pas été corrigé sur le Trello 😂

2022-01-21 08:21 UTC, EidanU commented on src/client/components/Menu/SideBarContent.tsx
> +    <Form action={"/post"}>
ho shit

2022-01-21 08:22 UTC, EidanU commented on src/client/components/Lesson/Post.tsx
> +  lesson: any;
D'acc

2022-05-20 15:56 UTC, SouchetJulie approved these changes

2022-05-20 15:57 UTC, merged