84 Utiliser le plugin Next pour ESLint
SouchetJulie/DevLab pull request #17
Opened 2022-01-30 10:05 UTC by SouchetJulie

## Internal
 * [eslint] Add Next plugin for ESLint

2022-02-21 07:14 UTC, alland07 commented
Il n'y a pas de pages /lesson, la liste des leçons se trouve sur la page principale, par contre, on a /lesson/index, est-ce que c'est à cela que tu fais référence?
@SouchetJulie

2022-02-21 08:09 UTC, alland07 requested changes
Le store est cassé, on ne peut plus accéder aux différentes pages une fois connecté

2022-02-21 17:23 UTC, SouchetJulie commented
> Il n'y a pas de pages /lesson, la liste des leçons se trouve sur la page principale, par contre, on a /lesson/index, est-ce que c'est à cela que tu fais référence? @SouchetJulie

Oui `/lesson/index`, et ça m'a fait remarqué au passage que j'avais oublié de le faire pour la page principale 😅 Le nouveau commit corrige ça ;)

> Le store est cassé, on ne peut plus accéder aux différentes pages une fois connecté

C'est bizarre, ça ne me fait pas ça ni en local, ni sur le déploiement. Tu as un screenshot de l'erreur ?

2022-03-08 11:54 UTC, alland07 approved these changes

2022-03-08 12:10 UTC, merged