93 Mettre TypeScript en "strict"
SouchetJulie/DevLab pull request #18
Opened 2022-02-06 15:34 UTC by SouchetJulie

## Internal
 * **[project] Set Typescript to "strict" and corrected all newly-raised errors**

2022-03-08 13:07 UTC, alland07 requested changes
Dans un premier temps faut résolve les conflicts, ensuite faut que les MTD testent l'app pour être sur que ça n'a rien pété. Si rien n'est cassé, je regarderai les 27 fichiers

2022-03-12 08:32 UTC, SouchetJulie commented
> Dans un premier temps faut résolve les conflicts, ensuite faut que les MTD testent l'app pour être sur que ça n'a rien pété. Si rien n'est cassé, je regarderai les 27 fichiers

Conflits réglés 👍 Et ça marche sur la preview

2022-03-12 09:01 UTC, alland07 commented
> > Dans un premier temps faut résolve les conflicts, ensuite faut que les MTD testent l'app pour être sur que ça n'a rien pété. Si rien n'est cassé, je regarderai les 27 fichiers
> 
> Conflits réglés 👍 Et ça marche sur la preview

 Nickel
J'attends quand même que les MTD testent.

2022-03-18 09:41 UTC, alland07 approved these changes
C'est validé

2022-03-18 09:41 UTC, merged