Reuse connection to DB
SouchetJulie/DevLab pull request #19
Opened 2022-02-12 12:56 UTC by SouchetJulie

## Improvement
 * [db] Re-use the same connection to database across hot reloads, instead of creating a new one at each application startup

2022-03-07 18:30 UTC, alland07 requested changes

2022-03-07 18:30 UTC, alland07 commented on src/server/services/database.service.ts
> +  console.log("[DB] Opened new connection to database");
Ce console.log est-il nécessaire? Ou alors un oubli?

2022-03-07 18:30 UTC, alland07 commented on src/server/services/database.service.ts
> +  console.log("[DB] Opened new connection to database");
Sinon code ok, fonctionnel ok.

2022-03-08 07:48 UTC, SouchetJulie commented on src/server/services/database.service.ts
> +  console.log("[DB] Opened new connection to database");
Ça sert pour les logs 😉

2022-03-08 11:51 UTC, merged