[client/lesson] Rework the upload form
SouchetJulie/DevLab pull request #4
Opened 2022-01-16 17:37 UTC by SouchetJulie

## Improvements
 * [lesson] Add CSS to the form (Bootstrap)
 * [lesson] Use AJAX for form upload (axios)
 * [lesson] Add alert on form upload to indicate success or error

2022-01-17 15:47 UTC, alland07 requested changes
Il faut changer l'alerte de quand on essaye d'upload alors qu'on est pas encore connecté, ou alors juste restreindre l'accès à la page aux personnes connectées

2022-01-17 15:47 UTC, EidanU requested changes
On a accès a la page d'Upload sans etre register, mais chaque import sera refusé du coup

2022-01-18 10:18 UTC, SouchetJulie commented
Vous voulez vraiment que je rajoute un garde-route dans cette PR ?!

2022-01-18 10:37 UTC, alland07 approved these changes
Bon pour moi

2022-01-18 10:38 UTC, merged