Paramétrage de profil
SouchetJulie/DevLab pull request #42
Opened 2022-06-29 16:35 UTC by SouchetJulie

## Summary
| Q            | A                                                     |
|--------------|-------------------------------------------------------|
| Bug fix?     | yes                                               |
| New feature? | yes |
| Issue?       | no |

## Changelog
### ✨ Features
* **[auth] Add a route to update the current user's profile (`PATCH /api/user`)**
* [auth] Updates the session cookie along with the database
### 👻 Internal
* [auth] Remove secure cookie in dev environment for Postman
### 🛠 Tools
 * [api] Configure Postman team & add a few requests

2022-07-02 19:37 UTC, SouchetJulie commented
![](https://github.trello.services/images/mini-trello-icon.png) [BACK](https://trello.com/c/jTh9Qpny/143-back)

2022-07-02 19:38 UTC, SouchetJulie commented
![](https://github.trello.services/images/mini-trello-icon.png) [Paramètrages de profil](https://trello.com/c/Oc1y3kMw/114-param%C3%A8trages-de-profil)

2022-07-08 08:12 UTC, EidanU reviewed
L'upload d'avatar ne fonctionne pas pour le moment :/

2022-07-08 10:19 UTC, alland07 requested changes

2022-07-08 10:19 UTC, alland07 commented on src/client/components/user/Dashboard.component.tsx
> +const Dashboard: FunctionComponent = () => {
C'est pas le dashboard ça normalement, c'est juste la page de modification du profil

2022-07-08 10:19 UTC, alland07 commented on src/client/components/user/Dashboard.component.tsx
> +const Dashboard: FunctionComponent = () => {
Du coup, il faudrait peut-être renommé les fichiers?

2022-07-08 10:19 UTC, alland07 commented on src/pages/api/user/index.ts
> +export const config = {
Cette const est dupliqué dans /api/lesson/index.ts, pourquoi ne pas simplement l'importer?

2022-07-08 10:19 UTC, alland07 commented on src/client/components/user/Dashboard.component.tsx
> +const Dashboard: FunctionComponent = () => {
Je précise que nous travaillons actuellement sur le composant dashboard du coup.

2022-07-08 10:19 UTC, alland07 commented on src/pages/user/index.tsx
> +export default () => <Dashboard />;
Du coup ici changer le nom du composant

2022-07-08 10:19 UTC, alland07 commented on src/server/common/parse-form.utils.ts
> +    if (value !== "" && value !== undefined && value !== null) {
```
Ne peut-on pas remplacer 
if (value !== "" && value !== undefined && value !== null)
par -> 
if (value) 
```

2022-07-08 10:19 UTC, alland07 commented on src/server/common/parse-form.utils.ts
> +  const valueExists = value !== undefined && value !== null && value !== "";
Ou alors mettre cette const en global dans le fichier? Ou sous la forme d'une fonction ?

2022-07-08 10:19 UTC, alland07 commented on src/server/common/parse-form.utils.ts
> +  const valueIsArray = Array.isArray(value);
J'ai pas envie de faire chier mais t'as pas typer ici alors que tu types partout ailleurs haha

2022-07-08 10:19 UTC, alland07 commented on src/server/common/parse-form.utils.ts
> +  const arrayValue = Array.isArray(value) ? value : [value];
pareil ici pour le type, tu ne type pas car pas sur du type que ça retourne?

2022-07-08 10:19 UTC, alland07 commented on src/server/services/storage.service.ts
> +const bucketName = process.env.NEXT_PUBLIC_BUCKET_NAME;
un ptit type string xD

2022-07-08 10:19 UTC, alland07 commented on src/server/services/storage.service.ts
> +const bucket = storage.bucket(bucketName);
Celui-ci aussi?

2022-07-08 10:19 UTC, alland07 commented on src/server/services/storage.service.ts
> +  const file = cleanFileMetadata(uploadFile);
Il y a un type pour les Files je crois

2022-07-08 10:19 UTC, alland07 commented on src/server/services/storage.service.ts
> +  const file = cleanFileMetadata(uploadFile);
Et celle de dessous ça doit etre un simple string je pense

2022-07-08 12:27 UTC, SouchetJulie commented on src/server/common/parse-form.utils.ts
> +  const valueIsArray = Array.isArray(value);
Celui-ci est un type guard ;)

2022-07-08 12:28 UTC, SouchetJulie commented on src/server/common/parse-form.utils.ts
> +  const valueExists = value !== undefined && value !== null && value !== "";
✔

2022-07-08 12:28 UTC, SouchetJulie commented on src/server/services/storage.service.ts
> +  const file = cleanFileMetadata(uploadFile);
✔

2022-07-08 12:28 UTC, SouchetJulie commented on src/server/services/storage.service.ts
> +const bucket = storage.bucket(bucketName);
✔

2022-07-08 12:28 UTC, SouchetJulie commented on src/server/services/storage.service.ts
> +const bucketName = process.env.NEXT_PUBLIC_BUCKET_NAME;
✔

2022-07-08 12:28 UTC, SouchetJulie commented on src/server/common/parse-form.utils.ts
> +  const arrayValue = Array.isArray(value) ? value : [value];
Nope, juste un oubli

2022-07-08 12:31 UTC, SouchetJulie commented on src/pages/api/user/index.ts
> +export const config = {
Parce que ça sert à configurer route par route : il se trouve juste que ces routes-là avaient besoin de la même config.
En plus, le fait de l'avoir en haut du fichier permet de voir du premier coup d'oeil comment c'est réglé

2022-07-08 12:32 UTC, SouchetJulie commented
> L'upload d'avatar ne fonctionne pas pour le moment :/

C'est quoi le problème, précisément ?

2022-07-08 12:33 UTC, SouchetJulie commented on src/client/components/user/Dashboard.component.tsx
> +const Dashboard: FunctionComponent = () => {
Je l'ai renommé en <Settings /> ✔

2022-07-08 12:54 UTC, alland07 submitted a review, later dismissed

2022-07-08 12:54 UTC, alland07 commented on src/server/common/parse-form.utils.ts
> +    if (value !== "" && value !== undefined && value !== null) {
Et du coup, on ne peut pas modifier pour faire en sorte que ce soit une fonction au début du fichier vu que tu utilises deux fois cette condition?

2022-07-08 12:59 UTC, alland07 approved these changes

2022-07-08 13:03 UTC, merged