41 Navbar
SouchetJulie/DevLab pull request #5
Opened 2022-01-16 22:26 UTC by SouchetJulie

## New
 * [client] Add a navbar present on all pages. It shows different links if the user is logged in...
![image](https://user-images.githubusercontent.com/90184650/149680511-63dedc02-4e89-4817-a228-d262691afca8.png)
... or not.
![image](https://user-images.githubusercontent.com/90184650/149680615-58a56692-50ce-4a65-b9d3-6a7d7a98fcda.png)

2022-01-19 15:01 UTC, alland07 submitted a review, later dismissed

2022-01-20 08:20 UTC, alland07 requested changes
![image](https://user-images.githubusercontent.com/55087762/150300018-b892f810-635f-4924-9db6-6e100ee0e459.png)
 Page de connexion, il faut enlever l'ascenseur @SouchetJulie

2022-01-20 09:31 UTC, alland07 requested changes
Dans l'ensemble c'est bon pour moi, regarde mon com ^^

2022-01-20 09:31 UTC, alland07 commented on src/client/components/signIn_signUp/LoginForm.component.tsx
> -      dispatch(addAlert({ message, success}));
Tu as oublier de modifier ici

2022-01-20 09:33 UTC, SouchetJulie commented on src/client/components/signIn_signUp/LoginForm.component.tsx
> -      dispatch(addAlert({ message, success}));
Done 👍

2022-01-20 10:28 UTC, alland07 requested changes
![image](https://user-images.githubusercontent.com/55087762/150321342-11579858-4b4a-4461-989c-020e841dc438.png)

2022-01-20 10:34 UTC, alland07 approved these changes

2022-01-20 10:36 UTC, merged