To merge landing page
SouchetJulie/DevLab pull request #6
Opened 2022-01-16 22:37 UTC by alland07

La PR est open mais il faut absolument faire une TRES GROSSE REVIEW. Eidan va doir fixe rapidement ce qui n'est pas/plus responsive donc en attendant Julie tu peux tester tout ce que tu as fait et qui doit fonctionner comme ça on rajoute dans ce code. 

Sachant que d'après ce que j'ai vu dans les packages, il y a moyen qu'on ait perdu pas mal de trucs.

Bon courage à tous LOL

2022-01-16 22:38 UTC, alland07 commented
Je pense qu'on devrait s'occuper de cette PR tous les 3 si possible

2022-01-19 08:46 UTC, EidanU commented
@SouchetJulie ca a l'air d'être good tu peux check

2022-01-19 09:02 UTC, SouchetJulie requested changes

2022-01-19 09:02 UTC, SouchetJulie commented on src/FakeDatas/LandingPage.cards.json
> +    "course": "All Classes"
Traduire ce texte en français :P

2022-01-19 09:14 UTC, EidanU commented on src/FakeDatas/LandingPage.cards.json
> +    "course": "All Classes"
Done, j'ai pas mis le texte en entier pour pas trop grossir la div en mobile et tablette

2022-01-19 09:23 UTC, SouchetJulie approved these changes

2022-01-19 09:23 UTC, merged