[WIP] create dashboard front / add fake data
SouchetJulie/DevLab pull request #66
Opened 2022-07-18 18:36 UTC by EidanU

## Summary
| Q            | A            |
|--------------|--------------|
| Bug fix?     | No      |
| New feature? | yes       |

## Changelog
### ✨ Features
* ** Create Dashboard**

2022-07-24 08:00 UTC, SouchetJulie commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard personnel](https://trello.com/c/CZX9xzCL/52-dashboard-personnel)

2022-07-24 10:20 UTC, SouchetJulie requested changes
Par pitié, lancez Prettier sur vos fichiers avant de push 🙏

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.grades ? user.grades : "Pas de classe"}</span>
![image](https://user-images.githubusercontent.com/90184650/180642170-76a21141-5ec7-4c8c-a97b-ae25f9ef7e0d.png)
Faut corriger l'affichage des classes, et adapter le singulier/pluriel selon le nombre

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +            <h6>{nbrPost} POSTS - 2 COMMENTAIRES</h6>
➕ c'était pas sur la maquette, mais afficher les matières enseignées aurait du sens aussi

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +        />
Afficher l'avatar s'il est présent, et ce placeholder s'il est absent

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +      <h3> Mon Profil</h3>
Faudrait uniformiser avec le titre sur la page d'upload, pour une charte graphique cohérente

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +import styles from "../../styles/dashboard/dashboard.module.scss";
```suggestion
import styles from "@styles/dashboard/dashboard.module.scss";
```

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/lesson/upload/form/LessonUploadFormMeta.component.tsx
> +      style={{ borderRadius: "15px" }}
À ce point-là autant écrire un fichier scss 😂

2022-07-24 10:20 UTC, SouchetJulie commented on src/pages/dashboard/index.tsx
> +  console.log("lessons :", lessons);
```suggestion
```

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +const DashBoardCard: FunctionComponent<Props> = ({ user, nbrPost }: Props) => {
`nbrPost` = `user.lessonIds.length`, du coup on peut enlever ce props

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/menu/UserLinks.tsx
> +        <Link href={"/dashboard"}>Mon dashboard</Link>
Dashboard -> "Mon profil"

2022-07-24 10:20 UTC, SouchetJulie commented on src/client/components/menu/UserLinks.tsx
>          <Link href={"/user/settings"}>Paramètres</Link>
Formulaire pour màj le profil -> "Paramètres"

2022-07-24 10:27 UTC, SouchetJulie requested changes

2022-07-24 10:27 UTC, SouchetJulie commented on src/client/styles/dashboard/dashboard.module.scss
> +.dashboardContainer {
![Capture d’écran 2022-07-24 à 12 25 30](https://user-images.githubusercontent.com/90184650/180642928-2636519f-3e46-4bfa-ad40-c40f109fd775.png)
Faut centrer et espacer en responsive

2022-07-24 10:29 UTC, SouchetJulie requested changes

2022-07-24 10:29 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.firstName ? user.firstName : "Votre nom"}</span>
```suggestion
            <span>{getUsername(user) ?? "Votre nom"}</span>
```
Vous l'avez sans doute pas vu mais il y a une fonction pour formatter le nom de l'utilisateur

2022-07-25 15:46 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.grades ? user.grades : "Pas de classe"}</span>
C'est good

2022-07-25 15:58 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +        />
Ca m'a l'air good mais comme je peux pas supp l'avatar depuis le formulaire, y'a pas trop moyen de check

2022-07-25 16:10 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +      <h3> Mon Profil</h3>
En vrai, j'ai un peu retouché pour avoir la meme taille pour les gros titres 'dashboard' et 'Créer une leçon' et les sous titre je les ai rétrécis. Mais question couleur, ca reste la mm chose, je trouve pas ca hyper choquant

2022-07-25 16:29 UTC, EidanU commented on src/client/components/lesson/upload/form/LessonUploadFormMeta.component.tsx
> +      style={{ borderRadius: "15px" }}
mdrr bah ca restera comme ca pour le moment, pq quoi qu'il arrive ca fera sale, donc vu qu'il n'y a qu'un seul element dans le style j'y touche pas pq ca encombre pas trop

2022-07-25 16:33 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +const DashBoardCard: FunctionComponent<Props> = ({ user, nbrPost }: Props) => {
good

2022-07-25 16:35 UTC, EidanU commented on src/client/components/menu/UserLinks.tsx
>          <Link href={"/user/settings"}>Paramètres</Link>
En soit ca reste une page de profil donc je pense pas qu'on doive changer le nom

2022-07-25 16:36 UTC, EidanU commented on src/client/components/menu/UserLinks.tsx
> +        <Link href={"/dashboard"}>Mon dashboard</Link>
Pareil que le commentaire d'en dessous

2022-07-25 17:32 UTC, SouchetJulie commented on src/client/components/menu/UserLinks.tsx
> +        <Link href={"/dashboard"}>Mon dashboard</Link>
Je pense qu'il y a un malentendu sur ce que je voulais dire : en l'état des choses on a un doublon "Mon profil" == "Dashboard" donc faut choisir l'un ou l'autre

2022-07-25 17:34 UTC, SouchetJulie commented on src/client/components/menu/UserLinks.tsx
>          <Link href={"/user/settings"}>Paramètres</Link>
La page de paramètres affiche un gros "TODO" à l'heure actuelle, donc soit on la vire et les paramètres deviennent "Mon profil", soit on met le composant de paramétrage dans "Paramètres"

2022-07-25 17:37 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +        />
C'est good
![image](https://user-images.githubusercontent.com/90184650/180839742-8a026531-029a-4340-918f-74ebbd4b1677.png)

2022-07-25 17:40 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +      <h3> Mon Profil</h3>
C'est surtout que c'est pas placé au même endroit :/
C'est pas bien compliqué, faut juste reprendre le style et ça évite d'avoir un titre qui se promène d'une page à l'autre

2022-07-25 17:42 UTC, SouchetJulie commented on src/pages/dashboard/index.tsx
> +  console.log(lessons && lessons);
Sérieux what 😂

2022-07-25 17:48 UTC, alland07 commented on src/client/components/menu/UserLinks.tsx
> +        <Link href={"/dashboard"}>Mon dashboard</Link>
En fait il y a la page dashboard et la page profil ('user') qui sont bien deux pages séparés
Par contre il ny a pas paramètrages

2022-07-25 18:17 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +            <h6>{nbrPost} POSTS - 2 COMMENTAIRES</h6>
On verra ça dans une autre PR au pire tkt

2022-07-26 15:51 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +      <h3> Mon Profil</h3>
En effet, c'est bon !

2022-07-26 15:53 UTC, EidanU commented on src/client/components/menu/UserLinks.tsx
>          <Link href={"/user/settings"}>Paramètres</Link>
Good

2022-07-26 15:56 UTC, EidanU commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.firstName ? user.firstName : "Votre nom"}</span>
hooooo

2022-07-26 15:56 UTC, EidanU commented on src/pages/dashboard/index.tsx
> +  console.log(lessons && lessons);
yes my bad

2022-07-26 16:51 UTC, SouchetJulie commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.firstName ? user.firstName : "Votre nom"}</span>
Tu as oublié ça ? 😂

2022-07-26 17:01 UTC, alland07 commented on src/client/components/dashboard/Card.tsx
> +            <span>{user.firstName ? user.firstName : "Votre nom"}</span>
C'est bon mdr

2022-07-26 17:20 UTC, SouchetJulie approved these changes

2022-07-26 17:22 UTC, merged