Filtrer les leçons
SouchetJulie/DevLab pull request #68
Opened 2022-07-24 16:32 UTC by SouchetJulie

## Summary
| Q            | A            |
|--------------|--------------|
| Bug fix?     | no       |
| New feature? | yes       |

## Changelog
### ✨ Features
* **[lesson] Add functional filter to lessons list on client-side**
### 🚀 Improvements
* [lesson] Prefetch lesson when hovering over a lesson item in list
* [front] Standardize page titles along with browser tab titles
* [front] Set minimum height to page content
### 👻 Internal
* [utils] Move some form parsing utility functions to `src/utils/`

2022-07-25 11:34 UTC, SouchetJulie commented
![](https://github.trello.services/images/mini-trello-icon.png) [Filtrer les leçons sur la page des leçons](https://trello.com/c/w4ti6rAR/169-filtrer-les-le%C3%A7ons-sur-la-page-des-le%C3%A7ons)

2022-07-25 16:40 UTC, alland07 requested changes
Je pense que l'on peut dégager ce truc du coup mdrrr :
![image](https://user-images.githubusercontent.com/55087762/180830258-13db727b-797b-4a24-b1de-71414f9aaa2e.png)
Et du coup ça aussi :
![image](https://user-images.githubusercontent.com/55087762/180830346-9e3cf6dd-24aa-4256-833f-ec1ed3c5bd12.png)

2022-07-25 16:47 UTC, alland07 commented
Le reste c'est bon

2022-07-25 16:48 UTC, alland07 commented
> Je pense que l'on peut dégager ce truc du coup mdrrr : ![image](https://user-images.githubusercontent.com/55087762/180830258-13db727b-797b-4a24-b1de-71414f9aaa2e.png) Et du coup ça aussi : ![image](https://user-images.githubusercontent.com/55087762/180830346-9e3cf6dd-24aa-4256-833f-ec1ed3c5bd12.png)

Le reste c'est bon

2022-07-25 20:34 UTC, SouchetJulie commented
To-do :

- [ ] ajouter un style au LessonItem qui sont des brouillons
- [ ] uniformiser le style du drop-down de sélection publié / brouillon

2022-07-26 10:21 UTC, alland07 approved these changes

2022-07-26 10:21 UTC, merged