Features/print
SouchetJulie/DevLab pull request #74
Opened 2022-07-25 16:33 UTC by alland07

## Summary
| Q            | A            |
|--------------|--------------|
| Bug fix?     | no       |
| New feature? | yes       |

## Changelog

New Features
### ✨ Features

The buttons for print and download a lesson can now be used !

![image](https://user-images.githubusercontent.com/55087762/180829001-040670b0-bd83-4848-9266-097b0fb5e7c2.png)

You can find those buttons inside any lesson.

2022-07-25 17:48 UTC, SouchetJulie requested changes
Si tu renommes en "favori" faut que le reste soit cohérent aussi : 
![image](https://user-images.githubusercontent.com/90184650/180841863-0591ad0b-e5ca-4a29-9848-f55cda2cd5bd.png)
- par ex, juste à gauche là tu as `/user/**bookmarks**`...
- du coup il y a les routes d'API et les interfaces à màj
- l'icône du bouton devrait devenir une étoile aussi

2022-07-25 17:50 UTC, alland07 commented
Je suis pas sur que l'on doive changer l'icône

2022-07-25 17:50 UTC, SouchetJulie commented
> Si tu renommes en "favori" faut que le reste soit cohérent aussi : ![image](https://user-images.githubusercontent.com/90184650/180841863-0591ad0b-e5ca-4a29-9848-f55cda2cd5bd.png)
> 
>     * par ex, juste à gauche là tu as `/user/**bookmarks**`...
> 
>     * du coup il y a les routes d'API et les interfaces à màj
> 
>     * l'icône du bouton devrait devenir une étoile aussi

Je suis pas contre le renommage mais faut pas faire les choses à moitié et laisser des choses bizarres traîner xD

2022-07-25 17:52 UTC, SouchetJulie commented
Je sais pas, moi tu me dis "favori", je pense à une étoile, pas à un marque-page

2022-07-25 17:52 UTC, SouchetJulie commented
Ou un cœur sinon

2022-07-26 07:50 UTC, SouchetJulie approved these changes

2022-07-26 07:50 UTC, merged